name: expense_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # bloc
  flutter_bloc: ^9.1.1
  bloc: ^9.2.0
  equatable: ^2.0.8

  # Routing
  go_router: ^17.0.1

  # DI
  get_it: ^9.2.0

  # flutter svg
  flutter_svg: ^2.2.3

  # cached_network_image
  cached_network_image: ^3.4.1

  # local db
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # internet checker
  connectivity_plus: ^6.1.5

  # graphql
  graphql_flutter: ^5.2.1

  # debugging
  logger: ^2.6.2

  # animation
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: DM Sans
      fonts:
        - asset: assets/fonts/DM_sans/regular.ttf
          weight: 400
        - asset: assets/fonts/DM_sans/thin.ttf
          weight: 300
        - asset: assets/fonts/DM_sans/semibold.ttf
          weight: 600
        - asset: assets/fonts/DM_sans/bold.ttf
          weight: 700
